A failed attempt to rebase to Ubuntu 14.04

diff --git a/Dockerfile.transmission b/Dockerfile.transmission
--- a/Dockerfile.transmission
+++ b/Dockerfile.transmission
@@ -3,14 +3,23 @@ FROM base:latest
 RUN dpkg-divert --local --rename --add /sbin/initctl
 RUN ln -s /bin/true /sbin/initctl
 
+RUN mv /bin/chmod /bin/chmod.orig
+RUN sh -c "echo '/bin/chmod.orig \"\$@\" || echo \"chmod failed, but we ignore\"' > /bin/chmod"
+RUN /bin/chmod.orig +x /bin/chmod
+
 RUN apt-get install -y transmission-daemon
-RUN apt-get install -y openssh-server
+RUN apt-get install -y passwd openssh-server
 RUN apt-get install -y vsftpd
-RUN mkdir /var/run/sshd
-RUN mkdir -p /var/run/vsftpd/empty
-RUN adduser --gecos "" --disabled-password user
-RUN adduser user sudo
+
+# Create user
+RUN useradd user
 RUN sh -c "echo \"$PASSWORD\n$PASSWORD\n\" | passwd user"
+
+# Set up SSH
+RUN mkdir -p /home/user/.ssh; ls -la /home/user ; chmod 700 /home/user/.ssh ; chown user /home/user/.ssh;
+RUN echo "user    ALL=(ALL)       ALL" >> /etc/sudoers.d/user
+
+RUN mkdir -p /var/run/vsftpd/empty
 
 ADD ./settings.json /var/lib/transmission-daemon/info/settings.json
 
@@ -23,6 +32,8 @@ EXPOSE $WEB_PORT:9091
 EXPOSE :$PEER_PORT
 EXPOSE $FTP_PORT:21
 EXPOSE :$FTP_PASV_PORT
-EXPOSE $SSH_PORT:22
+EXPOSE $SSH_PORT
 
-CMD /bin/bash -c "transmission-daemon -g /var/lib/transmission-daemon/info && ( vsftpd & ) && /usr/sbin/sshd -D"
+CMD /bin/bash -c "echo lala && mkdir -p /var/run/sshd && mkdir -p /var/run/vsftpd && transmission-daemon -g /var/lib/transmission-daemon/info && ( vsftpd & ) && /usr/sbin/sshd -d -D -p $SSH_PORT || echo fail"
+
+#CMD /bin/bash
